name: 'ebay_transform'
version: '1.0.0'
config-version: 2

profile: 'ebay_transform'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  ebay_transform:
    silver:
      +materialized: view
      +schema: silver
    gold:
      +materialized: table
      +schema: gold